-- ==============================================================================
-- Calc3D - Base de datos MASIVA de impresoras (+150 modelos)
-- ==============================================================================

-- 1. FDM: Consumo e Prosumer (As máis populares)
INSERT INTO printers (brand, model, wattage_w, type, verified) VALUES
-- Creality
('Creality', 'Ender 2', 150, 'FDM', true),
('Creality', 'Ender 2 Pro', 150, 'FDM', true),
('Creality', 'Ender 3', 270, 'FDM', true),
('Creality', 'Ender 3 Pro', 270, 'FDM', true),
('Creality', 'Ender 3 V2', 350, 'FDM', true),
('Creality', 'Ender 3 Max', 350, 'FDM', true),
('Creality', 'Ender 3 Neo', 350, 'FDM', true),
('Creality', 'Ender 3 V2 Neo', 350, 'FDM', true),
('Creality', 'Ender 3 Max Neo', 350, 'FDM', true),
('Creality', 'Ender 3 S1', 350, 'FDM', true),
('Creality', 'Ender 3 S1 Pro', 350, 'FDM', true),
('Creality', 'Ender 3 S1 Plus', 350, 'FDM', true),
('Creality', 'Ender 3 V3 SE', 350, 'FDM', true),
('Creality', 'Ender 3 V3 KE', 350, 'FDM', true),
('Creality', 'Ender 3 V3 Plus', 350, 'FDM', true),
('Creality', 'Ender 4', 270, 'FDM', true),
('Creality', 'Ender 5', 270, 'FDM', true),
('Creality', 'Ender 5 Pro', 270, 'FDM', true),
('Creality', 'Ender 5 Plus', 500, 'FDM', true),
('Creality', 'Ender 5 S1', 350, 'FDM', true),
('Creality', 'Ender 6', 350, 'FDM', true),
('Creality', 'Ender 7', 350, 'FDM', true),
('Creality', 'CR-10', 300, 'FDM', true),
('Creality', 'CR-10S', 300, 'FDM', true),
('Creality', 'CR-10S Pro', 480, 'FDM', true),
('Creality', 'CR-10S Pro V2', 480, 'FDM', true),
('Creality', 'CR-10 V2', 350, 'FDM', true),
('Creality', 'CR-10 V3', 350, 'FDM', true),
('Creality', 'CR-10 Max', 750, 'FDM', true),
('Creality', 'CR-10 Mini', 270, 'FDM', true),
('Creality', 'CR-10 Smart', 350, 'FDM', true),
('Creality', 'CR-10 Smart Pro', 350, 'FDM', true),
('Creality', 'CR-20', 270, 'FDM', true),
('Creality', 'CR-20 Pro', 270, 'FDM', true),
('Creality', 'CR-30 (Belt)', 350, 'FDM', true),
('Creality', 'CR-6 SE', 350, 'FDM', true),
('Creality', 'CR-6 Max', 500, 'FDM', true),
('Creality', 'K1', 350, 'FDM', true),
('Creality', 'K1 Max', 1000, 'FDM', true),
('Creality', 'K1C', 350, 'FDM', true),
('Creality', 'Sermoon D1', 350, 'FDM', true),
('Creality', 'Sermoon V1', 150, 'FDM', true),
('Creality', 'Sermoon V1 Pro', 150, 'FDM', true),

-- Anycubic
('Anycubic', 'Mega Zero', 150, 'FDM', true),
('Anycubic', 'Mega Zero 2.0', 250, 'FDM', true),
('Anycubic', 'Mega S', 250, 'FDM', true),
('Anycubic', 'Mega Pro', 300, 'FDM', true),
('Anycubic', 'Mega X', 350, 'FDM', true),
('Anycubic', 'Vyper', 350, 'FDM', true),
('Anycubic', 'Chiron', 600, 'FDM', true),
('Anycubic', 'Kobra', 400, 'FDM', true),
('Anycubic', 'Kobra Go', 400, 'FDM', true),
('Anycubic', 'Kobra Neo', 400, 'FDM', true),
('Anycubic', 'Kobra Plus', 500, 'FDM', true),
('Anycubic', 'Kobra Max', 500, 'FDM', true),
('Anycubic', 'Kobra 2', 400, 'FDM', true),
('Anycubic', 'Kobra 2 Neo', 400, 'FDM', true),
('Anycubic', 'Kobra 2 Pro', 400, 'FDM', true),
('Anycubic', 'Kobra 2 Plus', 400, 'FDM', true),
('Anycubic', 'Kobra 2 Max', 500, 'FDM', true),
('Anycubic', '4Max Pro 2.0', 350, 'FDM', true),

-- Elegoo
('Elegoo', 'Neptune', 300, 'FDM', true),
('Elegoo', 'Neptune 2', 300, 'FDM', true),
('Elegoo', 'Neptune 2S', 300, 'FDM', true),
('Elegoo', 'Neptune 2D', 300, 'FDM', true),
('Elegoo', 'Neptune 3', 300, 'FDM', true),
('Elegoo', 'Neptune 3 Pro', 300, 'FDM', true),
('Elegoo', 'Neptune 3 Plus', 400, 'FDM', true),
('Elegoo', 'Neptune 3 Max', 500, 'FDM', true),
('Elegoo', 'Neptune 4', 300, 'FDM', true),
('Elegoo', 'Neptune 4 Pro', 300, 'FDM', true),
('Elegoo', 'Neptune 4 Plus', 400, 'FDM', true),
('Elegoo', 'Neptune 4 Max', 500, 'FDM', true),

-- Artillery
('Artillery', 'Sidewinder X1', 300, 'FDM', true),
('Artillery', 'Sidewinder X2', 300, 'FDM', true),
('Artillery', 'Sidewinder X3 Pro', 300, 'FDM', true),
('Artillery', 'Sidewinder X3 Plus', 300, 'FDM', true),
('Artillery', 'Sidewinder X4 Pro', 300, 'FDM', true),
('Artillery', 'Sidewinder X4 Plus', 300, 'FDM', true),
('Artillery', 'Genius', 300, 'FDM', true),
('Artillery', 'Genius Pro', 300, 'FDM', true),
('Artillery', 'Hornet', 200, 'FDM', true),

-- Prusa Research
('Prusa', 'i3 MK2', 200, 'FDM', true),
('Prusa', 'i3 MK2S', 200, 'FDM', true),
('Prusa', 'i3 MK3', 250, 'FDM', true),
('Prusa', 'i3 MK3S', 250, 'FDM', true),
('Prusa', 'i3 MK3S+', 250, 'FDM', true),
('Prusa', 'MK4', 250, 'FDM', true),
('Prusa', 'MINI', 150, 'FDM', true),
('Prusa', 'MINI+', 150, 'FDM', true),
('Prusa', 'XL (1 to 5 heads)', 700, 'FDM', true),

-- Bambu Lab
('Bambu Lab', 'X1', 1000, 'FDM', true),
('Bambu Lab', 'X1-Carbon', 1000, 'FDM', true),
('Bambu Lab', 'X1E', 1000, 'FDM', true),
('Bambu Lab', 'P1P', 300, 'FDM', true),
('Bambu Lab', 'P1S', 350, 'FDM', true),
('Bambu Lab', 'A1', 300, 'FDM', true),
('Bambu Lab', 'A1 Mini', 150, 'FDM', true),

-- Sovol
('Sovol', 'SV01', 350, 'FDM', true),
('Sovol', 'SV01 Pro', 350, 'FDM', true),
('Sovol', 'SV02', 350, 'FDM', true),
('Sovol', 'SV03', 450, 'FDM', true),
('Sovol', 'SV04', 500, 'FDM', true),
('Sovol', 'SV05', 350, 'FDM', true),
('Sovol', 'SV06', 300, 'FDM', true),
('Sovol', 'SV06 Plus', 500, 'FDM', true),
('Sovol', 'SV07', 350, 'FDM', true),
('Sovol', 'SV07 Plus', 500, 'FDM', true),
('Sovol', 'SV08', 400, 'FDM', true),

-- Qidi Tech
('Qidi Tech', 'X-Smart', 150, 'FDM', true),
('Qidi Tech', 'X-Smart 3', 350, 'FDM', true),
('Qidi Tech', 'X-Plus', 350, 'FDM', true),
('Qidi Tech', 'X-Plus 3', 600, 'FDM', true),
('Qidi Tech', 'X-Max', 450, 'FDM', true),
('Qidi Tech', 'X-Max 3', 900, 'FDM', true),
('Qidi Tech', 'i-Fast', 700, 'FDM', true),
('Qidi Tech', 'i-Mate', 350, 'FDM', true),
('Qidi Tech', 'i-Mate S', 350, 'FDM', true),

-- Two Trees
('Two Trees', 'Sapphire Pro', 300, 'FDM', true),
('Two Trees', 'Sapphire Plus', 360, 'FDM', true),
('Two Trees', 'Bluer', 300, 'FDM', true),
('Two Trees', 'Bluer Plus', 360, 'FDM', true),
('Two Trees', 'Bluer RT', 300, 'FDM', true),
('Two Trees', 'SK1', 400, 'FDM', true),

-- Flying Bear / Kingroon
('Flying Bear', 'Ghost 4S', 300, 'FDM', true),
('Flying Bear', 'Ghost 5', 300, 'FDM', true),
('Flying Bear', 'Ghost 6', 300, 'FDM', true),
('Flying Bear', 'Reborn', 400, 'FDM', true),
('Flying Bear', 'Reborn 2', 400, 'FDM', true),
('Kingroon', 'KP3S', 150, 'FDM', true),
('Kingroon', 'KP3S Pro', 150, 'FDM', true),
('Kingroon', 'KP3S Pro V2', 200, 'FDM', true),
('Kingroon', 'KP5L', 300, 'FDM', true),
('Kingroon', 'KP5M', 300, 'FDM', true),
('Kingroon', 'KLP1', 300, 'FDM', true),

-- 2. Resina (SLA / MSLA / DLP)
-- Anycubic
('Anycubic', 'Photon', 50, 'Resina', true),
('Anycubic', 'Photon S', 50, 'Resina', true),
('Anycubic', 'Photon Zero', 30, 'Resina', true),
('Anycubic', 'Photon Mono', 45, 'Resina', true),
('Anycubic', 'Photon Mono SE', 55, 'Resina', true),
('Anycubic', 'Photon Mono X', 120, 'Resina', true),
('Anycubic', 'Photon Mono X 6K', 120, 'Resina', true),
('Anycubic', 'Photon Mono X 2', 120, 'Resina', true),
('Anycubic', 'Photon M3', 60, 'Resina', true),
('Anycubic', 'Photon M3 Plus', 120, 'Resina', true),
('Anycubic', 'Photon M3 Max', 150, 'Resina', true),
('Anycubic', 'Photon M5', 100, 'Resina', true),
('Anycubic', 'Photon M5s', 150, 'Resina', true),
('Anycubic', 'Photon Ultra (DLP)', 20, 'Resina', true),
('Anycubic', 'Photon D2 (DLP)', 20, 'Resina', true),

-- Elegoo
('Elegoo', 'Mars', 50, 'Resina', true),
('Elegoo', 'Mars Pro', 50, 'Resina', true),
('Elegoo', 'Mars 2', 50, 'Resina', true),
('Elegoo', 'Mars 2 Pro', 50, 'Resina', true),
('Elegoo', 'Mars 3', 50, 'Resina', true),
('Elegoo', 'Mars 3 Pro', 50, 'Resina', true),
('Elegoo', 'Mars 4', 50, 'Resina', true),
('Elegoo', 'Mars 4 Ultra', 50, 'Resina', true),
('Elegoo', 'Mars 4 Max', 70, 'Resina', true),
('Elegoo', 'Saturn', 120, 'Resina', true),
('Elegoo', 'Saturn S', 120, 'Resina', true),
('Elegoo', 'Saturn 2', 150, 'Resina', true),
('Elegoo', 'Saturn 3', 150, 'Resina', true),
('Elegoo', 'Saturn 3 Ultra', 150, 'Resina', true),
('Elegoo', 'Jupiter', 250, 'Resina', true),
('Elegoo', 'Jupiter SE', 250, 'Resina', true),

-- Phrozen
('Phrozen', 'Sonic Mini', 50, 'Resina', true),
('Phrozen', 'Sonic Mini 4K', 50, 'Resina', true),
('Phrozen', 'Sonic Mini 8K', 50, 'Resina', true),
('Phrozen', 'Sonic Mini 8K S', 50, 'Resina', true),
('Phrozen', 'Sonic Mighty 4K', 120, 'Resina', true),
('Phrozen', 'Sonic Mighty 8K', 150, 'Resina', true),
('Phrozen', 'Sonic Mega 8K', 250, 'Resina', true),
('Phrozen', 'Sonic Mega 8K S', 250, 'Resina', true),
('Phrozen', 'Shuffle', 100, 'Resina', true),
('Phrozen', 'Shuffle XL', 150, 'Resina', true),

-- Creality
('Creality', 'LD-002R', 70, 'Resina', true),
('Creality', 'LD-002H', 70, 'Resina', true),
('Creality', 'LD-006', 150, 'Resina', true),
('Creality', 'Halot-One', 100, 'Resina', true),
('Creality', 'Halot-One Plus', 100, 'Resina', true),
('Creality', 'Halot-One Pro', 100, 'Resina', true),
('Creality', 'Halot-Sky', 250, 'Resina', true),
('Creality', 'Halot-Lite', 150, 'Resina', true),
('Creality', 'Halot-Mage', 150, 'Resina', true),
('Creality', 'Halot-Mage Pro', 150, 'Resina', true),
('Creality', 'Halot-Ray', 150, 'Resina', true),

-- Peopoly
('Peopoly', 'Phenom', 350, 'Resina', true),
('Peopoly', 'Phenom L', 400, 'Resina', true),
('Peopoly', 'Phenom Noir', 350, 'Resina', true),
('Peopoly', 'Phenom Prime', 350, 'Resina', true),
('Peopoly', 'Phenom Forge', 350, 'Resina', true),
('Peopoly', 'Magneto X', 800, 'FDM', true),

-- 3. Profesionais e Industriais
-- Ultimaker / Formlabs / Raise3D / Flashforge / Zortrax / Markforged / Stratasys / BCN3D
('Ultimaker', 'Ultimaker 2', 200, 'FDM', true),
('Ultimaker', 'Ultimaker 2+', 220, 'FDM', true),
('Ultimaker', 'Ultimaker 2+ Connect', 220, 'FDM', true),
('Ultimaker', 'Ultimaker 3', 300, 'FDM', true),
('Ultimaker', 'Ultimaker 3 Extended', 300, 'FDM', true),
('Ultimaker', 'S3', 350, 'FDM', true),
('Ultimaker', 'S5', 500, 'FDM', true),
('Ultimaker', 'S7', 500, 'FDM', true),

('Formlabs', 'Form 1+', 65, 'SLA', true),
('Formlabs', 'Form 2', 65, 'SLA', true),
('Formlabs', 'Form 3', 65, 'SLA', true),
('Formlabs', 'Form 3+', 65, 'SLA', true),
('Formlabs', 'Form 3L', 100, 'SLA', true),
('Formlabs', 'Form 3B', 65, 'SLA', true),
('Formlabs', 'Form 3BL', 100, 'SLA', true),
('Formlabs', 'Fuse 1', 2000, 'SLS', true),

('Raise3D', 'N2', 600, 'FDM', true),
('Raise3D', 'N2 Plus', 600, 'FDM', true),
('Raise3D', 'Pro2', 600, 'FDM', true),
('Raise3D', 'Pro2 Plus', 600, 'FDM', true),
('Raise3D', 'Pro3', 600, 'FDM', true),
('Raise3D', 'Pro3 Plus', 600, 'FDM', true),
('Raise3D', 'E2', 350, 'FDM', true),
('Raise3D', 'E2CF', 350, 'FDM', true),
('Raise3D', 'Forge1', 1000, 'FDM', true),

('Flashforge', 'Adventurer 3', 150, 'FDM', true),
('Flashforge', 'Adventurer 4', 320, 'FDM', true),
('Flashforge', 'Adventurer 5M', 350, 'FDM', true),
('Flashforge', 'Creator Pro', 320, 'FDM', true),
('Flashforge', 'Creator Pro 2', 320, 'FDM', true),
('Flashforge', 'Creator 3', 500, 'FDM', true),
('Flashforge', 'Creator 3 Pro', 500, 'FDM', true),
('Flashforge', 'Creator 4', 1000, 'FDM', true),
('Flashforge', 'Guider II', 500, 'FDM', true),
('Flashforge', 'Guider IIS', 500, 'FDM', true),
('Flashforge', 'Guider 3', 500, 'FDM', true),
('Flashforge', 'Guider 3 Ultra', 650, 'FDM', true),

('Zortrax', 'M200', 320, 'FDM', true),
('Zortrax', 'M200 Plus', 320, 'FDM', true),
('Zortrax', 'M300', 500, 'FDM', true),
('Zortrax', 'M300 Plus', 500, 'FDM', true),
('Zortrax', 'M300 Dual', 500, 'FDM', true),
('Zortrax', 'Inventure', 300, 'FDM', true),
('Zortrax', 'Endureal', 1500, 'FDM', true),

('Markforged', 'Onyx One', 150, 'FDM', true),
('Markforged', 'Onyx Pro', 150, 'FDM', true),
('Markforged', 'Mark Two', 150, 'FDM', true),
('Markforged', 'X3', 300, 'FDM', true),
('Markforged', 'X5', 300, 'FDM', true),
('Markforged', 'X7', 300, 'FDM', true),

('Stratasys', 'F120', 1500, 'FDM', true),
('Stratasys', 'F170', 1500, 'FDM', true),
('Stratasys', 'F190', 1500, 'FDM', true),
('Stratasys', 'F270', 2500, 'FDM', true),
('Stratasys', 'F370', 2500, 'FDM', true),
('Stratasys', 'Fortus 250mc', 3000, 'FDM', true),
('Stratasys', 'Fortus 450mc', 3500, 'FDM', true),
('Stratasys', 'Fortus 900mc', 5000, 'FDM', true),
('Stratasys', 'J55', 1500, 'PolyJet', true),
('Stratasys', 'J750', 2000, 'PolyJet', true),
('Stratasys', 'J850', 2000, 'PolyJet', true),

('BCN3D', 'Sigma D25', 500, 'FDM', true),
('BCN3D', 'Sigmax R19', 500, 'FDM', true),
('BCN3D', 'Epsilon W27', 840, 'FDM', true),
('BCN3D', 'Epsilon W50', 840, 'FDM', true),

-- 4. Marcas "Frikis" e Kits DIY
('Voron', 'V0.1', 150, 'FDM', true),
('Voron', 'V0.2', 150, 'FDM', true),
('Voron', 'V1.8', 500, 'FDM', true),
('Voron', 'Trident', 500, 'FDM', true),
('Voron', 'V2.4 R2', 600, 'FDM', true),
('Voron', 'Switchwire', 350, 'FDM', true),

('Rat Rig', 'V-Core 3', 600, 'FDM', true),
('Rat Rig', 'V-Core 3.1', 800, 'FDM', true),
('Rat Rig', 'V-Minion', 200, 'FDM', true),

('Geeetech', 'A10', 250, 'FDM', true),
('Geeetech', 'A10M', 250, 'FDM', true),
('Geeetech', 'A10T', 250, 'FDM', true),
('Geeetech', 'A20', 350, 'FDM', true),
('Geeetech', 'A20M', 350, 'FDM', true),
('Geeetech', 'A20T', 350, 'FDM', true),
('Geeetech', 'A30', 500, 'FDM', true),
('Geeetech', 'Mecreator 2', 200, 'FDM', true),

('Tronxy', 'X5SA', 400, 'FDM', true),
('Tronxy', 'X5SA Pro', 400, 'FDM', true),
('Tronxy', 'X5SA-400', 600, 'FDM', true),
('Tronxy', 'X5SA-500', 800, 'FDM', true),
('Tronxy', 'Moore 1', 100, 'Ceramica', true),
('Tronxy', 'Moore 2', 100, 'Ceramica', true),

('Anet', 'A6', 200, 'FDM', true),
('Anet', 'A8', 200, 'FDM', true),
('Anet', 'A8 Plus', 300, 'FDM', true),
('Anet', 'ET4', 250, 'FDM', true),
('Anet', 'ET5 Pro', 350, 'FDM', true);
